"""V2 fixed wake listening preference

Revision: 6c9c73ac0555
"""

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

revision = "6c9c73ac0555"
down_revision = "ede2ec59ed9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_setting",
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("wake_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_setting")
    # ### end Alembic commands ###
