"""V2 explicit personal memory and user settings

Revision: ede2ec59ed9a
"""

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

revision = "ede2ec59ed9a"
down_revision = "675b403091a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_setting",
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "personal_memory",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "content_hash"),
    )
    op.create_index(
        op.f("ix_personal_memory_user_id"), "personal_memory", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_personal_memory_user_id"), table_name="personal_memory")
    op.drop_table("personal_memory")
    op.drop_table("memory_setting")
    # ### end Alembic commands ###
